services:
  web:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: inception_web
    image: web
    restart: always
    env_file:
      - ".env"
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - app
    networks:
      - inception_network

  admin:
    build: 
      context: ./bonus/adminer
      dockerfile: Dockerfile
    container_name: inception_admin
    image: admin
    restart: always
    # ports:
    #   - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - inception_network
  cache:
    build: 
      context: ./bonus/redis
      dockerfile: Dockerfile
    container_name: inception_cache
    image: cache
    restart: always
    # ports:
    #   - "6379:6379"
    expose:
      - "6379"
    depends_on:
      - db
    networks:
      - inception_network

  db:
    build: 
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: inception_db
    image: db
    restart: unless-stopped
    env_file:
      - ".env"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    # ports:
    #   - "3306:3306"
    expose:
      - "3306"

  app:
    build: 
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: inception_app
    image: app
    restart: always
    # ports:
    #   - "9000:9000"
    expose:
      - "9000"
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ".env"
    depends_on:
      - db
      - cache
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge
  
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress